"""phase 3 workout plans

Revision ID: 56bf9dbfc474
Revises: d44b3eb07b46
Create Date: 2026-08-31 02:33:37.295116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '56bf9dbfc474'
down_revision: Union[str, Sequence[str], None] = 'd44b3eb07b46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workout_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('day_of_week', sa.String(length=10), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('target_muscles', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('order_index', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_workout_plans_user', 'workout_plans', ['user_id'], unique=False)
    op.create_index('ix_workout_plans_user_day', 'workout_plans', ['user_id', 'day_of_week'], unique=False)
    op.create_table('workout_exercises',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workout_id', sa.UUID(), nullable=False),
    sa.Column('exercise_id', sa.UUID(), nullable=False),
    sa.Column('order_index', sa.Integer(), server_default='0', nullable=False),
    sa.Column('planned_sets', sa.Integer(), server_default='3', nullable=False),
    sa.Column('planned_reps_min', sa.Integer(), nullable=True),
    sa.Column('planned_reps_max', sa.Integer(), nullable=True),
    sa.Column('planned_weight_kg', sa.Numeric(precision=7, scale=3), nullable=True),
    sa.Column('planned_rir', sa.Integer(), nullable=True),
    sa.Column('superset_group', sa.String(length=8), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('planned_reps_min is null or planned_reps_max is null or planned_reps_min <= planned_reps_max', name='ck_we_rep_range'),
    sa.CheckConstraint('planned_sets >= 1 and planned_sets <= 20', name='ck_we_sets'),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workout_id'], ['workout_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_workout_exercises_plan', 'workout_exercises', ['workout_id', 'order_index'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_workout_exercises_plan', table_name='workout_exercises')
    op.drop_table('workout_exercises')
    op.drop_index('ix_workout_plans_user_day', table_name='workout_plans')
    op.drop_index('ix_workout_plans_user', table_name='workout_plans')
    op.drop_table('workout_plans')
    # ### end Alembic commands ###
