"""phase 4 sessions and sets

Revision ID: 699684ca26cf
Revises: 56bf9dbfc474
Create Date: 2026-08-31 02:37:49.804048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '699684ca26cf'
down_revision: Union[str, Sequence[str], None] = '56bf9dbfc474'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workout_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('workout_id', sa.UUID(), nullable=True),
    sa.Column('plan_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='in_progress', nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workout_id'], ['workout_plans.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sessions_user_date', 'workout_sessions', ['user_id', 'date'], unique=False)
    op.create_index('uq_sessions_one_active', 'workout_sessions', ['user_id'], unique=True, postgresql_where=sa.text("status = 'in_progress' and deleted_at is null"))
    op.create_table('session_exercises',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('exercise_id', sa.UUID(), nullable=False),
    sa.Column('order_index', sa.Integer(), server_default='0', nullable=False),
    sa.Column('planned_sets', sa.Integer(), nullable=True),
    sa.Column('planned_reps_min', sa.Integer(), nullable=True),
    sa.Column('planned_reps_max', sa.Integer(), nullable=True),
    sa.Column('replaced_from_exercise_id', sa.UUID(), nullable=True),
    sa.Column('superset_group', sa.String(length=8), nullable=True),
    sa.Column('skipped', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['replaced_from_exercise_id'], ['exercises.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['session_id'], ['workout_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_session_exercises_session', 'session_exercises', ['session_id', 'order_index'], unique=False)
    op.create_table('sets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('session_exercise_id', sa.UUID(), nullable=False),
    sa.Column('exercise_id', sa.UUID(), nullable=False),
    sa.Column('set_number', sa.Integer(), nullable=False),
    sa.Column('weight_kg', sa.Numeric(precision=7, scale=3), nullable=True),
    sa.Column('reps', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('distance_m', sa.Numeric(precision=9, scale=2), nullable=True),
    sa.Column('rir', sa.Integer(), nullable=True),
    sa.Column('rpe', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('failure', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('set_type', sa.String(length=20), server_default='working', nullable=False),
    sa.Column('rest_seconds', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('performed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('duration_seconds is null or duration_seconds >= 0', name='ck_sets_duration'),
    sa.CheckConstraint('reps is null or (reps >= 0 and reps <= 1000)', name='ck_sets_reps'),
    sa.CheckConstraint('rir is null or (rir >= 0 and rir <= 10)', name='ck_sets_rir'),
    sa.CheckConstraint('rpe is null or (rpe >= 1 and rpe <= 10)', name='ck_sets_rpe'),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['session_exercise_id'], ['session_exercises.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['workout_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sets_session', 'sets', ['session_id'], unique=False)
    op.create_index('ix_sets_user_exercise', 'sets', ['user_id', 'exercise_id', 'performed_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sets_user_exercise', table_name='sets')
    op.drop_index('ix_sets_session', table_name='sets')
    op.drop_table('sets')
    op.drop_index('ix_session_exercises_session', table_name='session_exercises')
    op.drop_table('session_exercises')
    op.drop_index('uq_sessions_one_active', table_name='workout_sessions', postgresql_where=sa.text("status = 'in_progress' and deleted_at is null"))
    op.drop_index('ix_sessions_user_date', table_name='workout_sessions')
    op.drop_table('workout_sessions')
    # ### end Alembic commands ###
