"""exercise image gallery

Revision ID: 7c8ed6253f9d
Revises: e5921caf985d
Create Date: 2026-08-31 03:44:07.888948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7c8ed6253f9d'
down_revision: Union[str, Sequence[str], None] = 'e5921caf985d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('image_urls', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercises', 'image_urls')
    # ### end Alembic commands ###
