"""phase 2 exercises and ingest runs

Revision ID: d44b3eb07b46
Revises: 24289db459f8
Create Date: 2026-08-31 02:04:16.147474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd44b3eb07b46'
down_revision: Union[str, Sequence[str], None] = '24289db459f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingest_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='running', nullable=False),
    sa.Column('rows_seen', sa.Integer(), server_default='0', nullable=False),
    sa.Column('rows_written', sa.Integer(), server_default='0', nullable=False),
    sa.Column('rows_rejected', sa.Integer(), server_default='0', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exercises',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('source_id', sa.String(length=120), nullable=True),
    sa.Column('source_version', sa.String(length=40), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('name_normalized', sa.String(length=200), nullable=False),
    sa.Column('aliases', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('body_part', sa.String(length=40), nullable=False),
    sa.Column('primary_muscle', sa.String(length=40), nullable=False),
    sa.Column('secondary_muscles', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('equipment', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('metric_type', sa.String(length=30), server_default='weight_reps', nullable=False),
    sa.Column('bodyweight_load_factor', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('default_rest_seconds', sa.Integer(), server_default='120', nullable=False),
    sa.Column('instructions', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('gif_url', sa.Text(), nullable=True),
    sa.Column('video_url', sa.Text(), nullable=True),
    sa.Column('media_licence', sa.String(length=120), nullable=True),
    sa.Column('is_custom', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('owner_user_id', sa.UUID(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(is_custom = false and owner_user_id is null) or (is_custom = true and owner_user_id is not null)', name='ck_exercise_custom_owner'),
    sa.CheckConstraint('bodyweight_load_factor is null or (bodyweight_load_factor >= 0 and bodyweight_load_factor <= 2)', name='ck_exercise_bw_factor'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_id', name='uq_exercise_source')
    )
    op.create_index('ix_exercises_body_part', 'exercises', ['body_part'], unique=False)
    op.create_index('ix_exercises_equipment', 'exercises', ['equipment'], unique=False, postgresql_using='gin')
    op.create_index('ix_exercises_name_normalized', 'exercises', ['name_normalized'], unique=False)
    op.create_index('ix_exercises_owner', 'exercises', ['owner_user_id'], unique=False)
    op.create_index('ix_exercises_primary_muscle', 'exercises', ['primary_muscle'], unique=False)
    op.create_index('ix_exercises_secondary', 'exercises', ['secondary_muscles'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_exercises_secondary', table_name='exercises', postgresql_using='gin')
    op.drop_index('ix_exercises_primary_muscle', table_name='exercises')
    op.drop_index('ix_exercises_owner', table_name='exercises')
    op.drop_index('ix_exercises_name_normalized', table_name='exercises')
    op.drop_index('ix_exercises_equipment', table_name='exercises', postgresql_using='gin')
    op.drop_index('ix_exercises_body_part', table_name='exercises')
    op.drop_table('exercises')
    op.drop_table('ingest_runs')
    # ### end Alembic commands ###
