"""phase 6 personal records and session summaries

Revision ID: e5921caf985d
Revises: 9e348993d1d7
Create Date: 2026-08-31 03:05:05.617613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e5921caf985d'
down_revision: Union[str, Sequence[str], None] = '9e348993d1d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_summaries',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('total_exercises', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total_sets', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total_reps', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total_volume_kg', sa.Numeric(precision=12, scale=3), server_default='0', nullable=False),
    sa.Column('total_duration_seconds', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total_distance_m', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('muscles_trained', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('prs_achieved', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['workout_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index('ix_session_summaries_user', 'session_summaries', ['user_id'], unique=False)
    op.create_table('personal_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('exercise_id', sa.UUID(), nullable=False),
    sa.Column('record_type', sa.String(length=30), nullable=False),
    sa.Column('qualifier', sa.Numeric(precision=7, scale=3), server_default='0', nullable=False),
    sa.Column('value', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=True),
    sa.Column('weight_kg', sa.Numeric(precision=7, scale=3), nullable=True),
    sa.Column('set_id', sa.UUID(), nullable=True),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('achieved_on', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['workout_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['set_id'], ['sets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'exercise_id', 'record_type', 'qualifier', name='uq_pr_slot')
    )
    op.create_index('ix_pr_user_exercise', 'personal_records', ['user_id', 'exercise_id', 'record_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pr_user_exercise', table_name='personal_records')
    op.drop_table('personal_records')
    op.drop_index('ix_session_summaries_user', table_name='session_summaries')
    op.drop_table('session_summaries')
    # ### end Alembic commands ###
